
trigger:
- none

pool: gtvagentpool

stages:
  - stage: gtv_app_release
    jobs:
      - job: 
        steps:
          - task: NodeTool@0
            displayName: set node 15.8
            inputs:
              versionSpec: 15.8.0
          - task: Npm@1
            displayName: npm install
            inputs:
              workingDir: $(System.DefaultWorkingDirectory)
              verbose: true
              customCommand: 'ci'
          - task: Npm@1
            displayName: npm run build
            inputs:
              command: custom
              workingDir: '$(System.DefaultWorkingDirectory)'
              verbose: true
              customCommand: 'run build:gtvprod'

          - task: Docker@2
            displayName: build push docker image
            inputs:
              containerRegistry: gummybearscr
              repository: gtvapp
              Dockerfile: Dockerfile
